name: CI

on:
  #push:
    branches: [ main, dev ]
  #pull_request:
    branches: [ main, dev ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (runtime + dev tools)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.5.* black==24.* bandit==1.7.*

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Bandit (security lint)
        run: bandit -q -r app tools || true
        # Note: Bandit is informational; fail-on issues? remove '|| true'

      # ---- Docker build (no push) ----
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: plantdeck:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: quick vulnerability scan of the workspace (fs mode)
      - name: Trivy (filesystem scan)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: .
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
