name: Docker Publish

on:
  #push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # needed to push to GHCR

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/plantdeck_rag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          VERSION_TAG="${GITHUB_REF_NAME}"
          SHA_TAG="${GITHUB_SHA::7}"
          echo "version=${VERSION_TAG}" >> $GITHUB_OUTPUT
          echo "sha=${SHA_TAG}" >> $GITHUB_OUTPUT

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Trivy scan the pushed image
      - name: Trivy (image scan)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
